version: '3.7'

services:
  web:
    platform: linux/amd64
    build: ./django_server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_server:/app
      - ./media:/app/media
      - ./kafka2api/ca.pem:/app/ca.pem:ro
      - ./kafka2api/FVHIoT-python/fvhiot:/app/fvhiot
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
      - ./kafka2api.env
    depends_on:
      - db

  db:
    image: postgis/postgis
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

  react:
    build: ./react_ui
    command: yarn start
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./react_ui/src/:/app/src
      - ./react_ui/public/:/app/public
