# Generated by Django 3.2.10 on 2021-12-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('color', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('green', 'green'), ('red', 'red')], default='primary', max_length=32)),
                ('icon', models.FileField(upload_to='')),
                ('published', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
