# Generated by Django 3.2.10 on 2022-01-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_map', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='button_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
