# Generated by Django 3.2.10 on 2022-01-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_map', '0003_tag_button_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
