# Generated by Django 3.2.10 on 2022-05-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_map', '0004_alter_tag_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('yellow', 'yellow'), ('green', 'green')], default='blue', max_length=32),
        ),
    ]
