# Generated by Django 3.2.10 on 2022-05-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_map', '0005_alter_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdatapoint',
            name='device_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
