# Generated by Django 3.2.18 on 2023-02-28 09:00

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations


def update_point(apps, schema_editor):
    MapDataPoint = apps.get_model("feedback_map", "MapDataPoint")
    for point in MapDataPoint.objects.all():
        point.point = Point((point.lon, point.lat), srid=4326)
        point.save()


class Migration(migrations.Migration):
    dependencies = [
        ('feedback_map', '0006_mapdatapoint_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdatapoint',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.RunPython(update_point),
    ]
