# Generated by Django 3.2.18 on 2023-03-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_map', '0007_mapdatapoint_add_geom_geog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('yellow', 'yellow'), ('green', 'green'), ('white', 'white')], default='blue', max_length=32),
        ),
    ]
