# Generated by Django 3.2.18 on 2023-09-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_map', '0008_alter_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdatapoint',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('CLOSED', 'Closed'), ('OBSOLETE', 'Obsolete'), ('REOPENED', 'Reopened')], default='NEW', max_length=32),
        ),
    ]
